run:
  deadline: 5m
  skip-dirs:
    - mock*
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  exclude-rules:
    - path: internal/test/
      linters:
        - golint
    - path: cloudtest\.go
      linters:
        - golint
    - path: api/v1alpha2/types\.go
      linters:
        - golint
    - path: _test\.go
      linters:
        - unused
  include:
  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0
