apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: flannel-windows
  namespace: default
spec:
  strategy: "ApplyOnce"
  clusterSelector:
    matchLabels:
      cni: flannel-windows
  resources:
    - name: flannel-windows-addon
      kind: ConfigMap
